server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      #uri: http://localhost:8888
      profile: prod
      username: admin
      password: secret_pass
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"