server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luciano-ferretto/udemy-curso
          default-label: main
          search-paths:
          - 'configs/greeting-service*'

          #username: username
          #password: password